// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Refmt = require("../src/Refmt.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var ocamlCode = "\n  let x =\n    match 42 with \n    | .1 -> 4\n    | _ -> 2\n";

var param = Refmt.parseML(ocamlCode);

var reasonCode;

if (param.tag) {
  console.log("Error: ", param[0][1][/* message */0]);
  reasonCode = /* () */0;
} else {
  reasonCode = Pervasives.failwith("unreachable");
}

exports.ocamlCode = ocamlCode;
exports.reasonCode = reasonCode;
/* param Not a pure module */
